<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'APWF',
  'author' => 'Pedro Alberto Bazan Serrano',
  'description' => 'Modulo para la gestión de workflows',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Workflow',
  'published_date' => '2012-03-12 21:35:54',
  'type' => 'module',
  'version' => 1331588154,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Workflow',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'APWF_Detonadores',
      'class' => 'APWF_Detonadores',
      'path' => 'modules/APWF_Detonadores/APWF_Detonadores.php',
      'tab' => false,
    ),
    1 => 
    array (
      'module' => 'APWF_Workflows',
      'class' => 'APWF_Workflows',
      'path' => 'modules/APWF_Workflows/APWF_Workflows.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/apwf_workflows_apwf_detonadores_APWF_Workflows.php',
      'to_module' => 'APWF_Workflows',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/apwf_workflows_apwf_detonadoresMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/APWF_Detonadores',
      'to' => 'modules/APWF_Detonadores',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/APWF_Workflows',
      'to' => 'modules/APWF_Workflows',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/APWF_Detonadores.php',
      'to_module' => 'APWF_Detonadores',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/APWF_Detonadores.php',
      'to_module' => 'APWF_Detonadores',
      'language' => 'es_es',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/APWF_Workflows.php',
      'to_module' => 'APWF_Workflows',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/APWF_Workflows.php',
      'to_module' => 'APWF_Workflows',
      'language' => 'es_es',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_es.lang.php',
      'to_module' => 'application',
      'language' => 'es_es',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/apwf_workflows_apwf_detonadores_APWF_Detonadores.php',
      'to_module' => 'APWF_Detonadores',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/apwf_workflows_apwf_detonadores_APWF_Workflows.php',
      'to_module' => 'APWF_Workflows',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
	),
	'logic_hooks'	=>
	array(
		array(
			'module' 				=> '',
			'hook' 					=> 'before_save',
			'order' 				=> '10',
			'description' 	=> 'carga datos previos del bean',
			'file' 					=> 'modules/APWF_Workflows/APWF_WorkflowHooks.php',
			'class'					=> 'APWF_WorkflowHooks',
			'function'			=> 'cargaPreDataWorkflow',			
		),
		array(
			'module' 				=> '',
			'hook' 					=> 'delete_save',
			'order' 				=> '10',
			'description' 	=> 'carga datos previos del bean',
			'file' 					=> 'modules/APWF_Workflows/APWF_WorkflowHooks.php',
			'class'					=> 'APWF_WorkflowHooks',
			'function'			=> 'cargaPreDataWorkflow',			
		),
		array(
			'module' 				=> '',
			'hook' 					=> 'after_save',
			'order' 				=> '20',
			'description' 	=> 'execute workflow',
			'file' 					=> 'modules/APWF_Workflows/APWF_WorkflowHooks.php',
			'class'					=> 'APWF_WorkflowHooks',
			'function'			=> 'ejecutaWorkflow',			
		),
		array(
			'module' 				=> '',
			'hook' 					=> 'after_delete',
			'order' 				=> '20',
			'description' 	=> 'execute workflow',
			'file' 					=> 'modules/APWF_Workflows/APWF_WorkflowHooks.php',
			'class'					=> 'APWF_WorkflowHooks',
			'function'			=> 'ejecutaWorkflow',				
		),
	)
);
